---
name: Padre-Plugin-Catalyst
version: 0.05
author:
  - 'Breno G. de Oliveira <garu@cpan.org>'
abstract: Simple Catalyst helper interface for Padre
license: perl
resources:
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-Catalyst/
build_requires:
  Catalyst::Devel: 1
  Module::Build: 0.3
  Module::Pluggable::Object: 3.9
  Padre: 0.43
  Test::More: 0
configure_requires:
  Module::Build: 0.35
  Padre::PluginBuilder: 0.12
provides:
  Padre::Plugin::Catalyst:
    file: lib/Padre/Plugin/Catalyst.pm
    version: 0.05
  Padre::Plugin::Catalyst::Helper:
    file: lib/Padre/Plugin/Catalyst/Helper.pm
    version: 0.05
  Padre::Plugin::Catalyst::NewApp:
    file: lib/Padre/Plugin/Catalyst/NewApp.pm
    version: 0.05
  Padre::Plugin::Catalyst::Util:
    file: lib/Padre/Plugin/Catalyst/Util.pm
    version: 0.05
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
